from gturtle import *
Karl = Turtle()
Karl.setPenColor("black")
Karl.setLineWidth(80)
Karl.forward(100)
Karl.right(180)
Karl.penUp()
Karl.forward(40)
Karl.penDown()
Karl.setPenColor("green")
Karl.dot(20)
Karl.penUp()
Karl.forward(10)
Karl.penDown()
Karl.setPenColor("yellow")
Karl.dot(20)
Karl.penUp()
Karl.forward(40)
Karl.penDown()
Karl.setPenColor("red")
Karl.dot(20)